```{r, label = 'DEPENDENCIES'}
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r, label ='READ IN DATA SET'}
mpg_data <- read.csv("MechaCar_mpg.csv", check.names = F, stringsAsFactors = F)
```

```{r, label = 'LINEAR REGRESSION'}
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, mpg_data)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, mpg_data))
```

```{r, label = 'SUSPENSION COIL DATA'}
coils <- read.csv("Suspension_Coil.csv", check.names = F, stringsAsFactors = F)

# summarize coil PSI data and group by lot
total_summary <- coils %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))

lot_summary <- coils %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI))
```

```{r, label = 'T-TEST ON SUSPENSION COILS'}
t.test(coils$PSI, mu= 1500)

```

```{r, label = 'T-TEST COIL PSI BY LOT'}
lot1 <- subset(coils, Manufacturing_Lot =="Lot1")
t.test(lot1$PSI, mu=1500)
# OR
# t.test(subset(coils$PSI, coils$Manufacturing_Lot == "Lot1"), mu=1500)

lot2 <- subset(coils, Manufacturing_Lot =="Lot2")
t.test(lot2$PSI, mu=1500)
# OR 
# t.test(subset(coils$PSI, coils$Manufacturing_Lot == "Lot2"), mu=1500)

lot3 <- subset(coils, Manufacturing_Lot =="Lot3")
t.test(lot3$PSI, mu=1500)
# OR
# t.test(subset(coils$PSI, coils$Manufacturing_Lot == "Lot3"), mu=1500)

```

